### ISSUE TITLE
move this git back to piwik_ynh ? 

### ISSUE THREAD

**Issue by polytan02** [maniackcrudelis/piwik_ynh#1]
Serait il possible de supprimer l'ancien git et de le recréer ? 
Sinon il faut changer la page de doc et puis il n'y a rien de nouveau à part que le dépôt fonctionne ;)

**Comment by maniackcrudelis** [comment]
J'attends de m'assurer que ce dépôt fonctionne correctement, puis je remplacerais l'ancien par celui-ci.

**Comment by maniackcrudelis** [comment]
Ce nouveau dépôt est encore buggé!
Je sais pas ce que github a contre piwik...
