### ISSUE TITLE
Nombreuses erreurs après installation

### ISSUE THREAD

**Issue by LeOSW42** [maniackcrudelis/piwik_ynh#3]
De nombreuses erreur après l'instalation (en console pour avoir une idée de l'avancement)

Après une erreur nginx sur le temps d'attente, j'ai ça :

> Error: no website was found in this Piwik installation.
> Check the table 'piwik_site' in your database, it should contain your Piwik websites.

Quand je clique sur Login de la page d'erreur, j'ai ça :

> The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Piwik.

**Comment by maniackcrudelis** [comment]
Je ne constate aucune erreur sur un essai à l'instant. Peux-tu m'indiquer exactement les conditions de ton installation?
Et, si tu l'as encore, me joindre ton log d'installation.

**Comment by LeOSW42** [comment]
Paste envoyé par message privé

**Comment by maniackcrudelis** [comment]
Bien reçu

**Comment by maniackcrudelis** [comment]
Ton log parait normal, et un essai dans des conditions similaires aux tiennes fonctionne toujours sans problème de mon côté.

L'erreur nginx liée au temps disait quoi? Et a quel moment?

**Comment by LeOSW42** [comment]
A noter que leo est un utilisateur UNIX et YunoHost

En fait l'erreur nginx a eu lieu pendant l'install (vers la fin). C'est
Gateway timeout.

Léo

Le 18/01/2015 18:37, Maniack Crudelis a écrit :
>
> Ton log parait normal, et un essai dans des conditions similaires aux
> tiennes fonctionne toujours sans problème de mon côté.
>
> L'erreur nginx liée au temps disait quoi? Et a quel moment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maniackcrudelis/piwik_ynh/issues/3#issuecomment-70417242>.
>

-- 
Léo SERRE
  06.18.62.32.05
  leo-serre.legtux.org

**Comment by maniackcrudelis** [comment]
piwik_site est renseigné à cette ligne
https://github.com/maniackcrudelis/piwik_ynh/blob/master/scripts/install#L94
C'est l'appel curl qui s'occupe de cela.

Si il y a eu erreur nginx, je suppose que c'était lors d'une installation via le panel admin de yunohost? Sur ton log en ligne de commande, je ne vois aucune erreur nginx.

Un gateway timeout peut tout à fait avoir provoqué une erreur lors de l'installation, et donc empêcher l'exécution de toutes les tâches nécessaires.
Ta machine dispose-t-elle de ressources système limitée? Ou d'une connexion internet lente? L'installation de piwik est plutôt longue, quelques minutes chez moi, mais je n'obtiens pas pour autant de timeout.

As-tu retenté l'installation par la suite?

**Comment by LeOSW42** [comment]
J'ai effectivement des ressources limitées, mais je pense suffisantes :

CPU : 1 coeur de Xeon 5
RAM : 1 Go
DD : 64 Go

Je retente une dernière fois ;)

**Comment by LeOSW42** [comment]
Ça a marché, je close. Étrange tout de même.

**Comment by maniackcrudelis** [comment]
Si tu as installé depuis le panel admin, ce n'est pas si surprenant. Il me semble que le timeout est un peu bas, c'est un problème qui est déjà survenu chez d'autres utilisateurs.
Et le timeout peut-être fatal lors de l'install!
Au moins, pas de véritable problème du côté de l'app, c'est déjà bien.

**Comment by LeOSW42** [comment]
J'ai installé depuis la console, pour avoir une idée de l'avancement.

Léo

Le 19/01/2015 10:59, Maniack Crudelis a écrit :
>
> Si tu as installé depuis le panel admin, ce n'est pas si surprenant.
> Il me semble que le timeout est un peu bas, c'est un problème qui est
> déjà survenu chez d'autres utilisateurs.
> Et le timeout peut-être fatal lors de l'install!
> Au moins, pas de véritable problème du côté de l'app, c'est déjà bien.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maniackcrudelis/piwik_ynh/issues/3#issuecomment-70469424>.
>

-- 
Léo SERRE
  leo-serre.legtux.org
