### ISSUE TITLE
Username with less than 3 letters \ nom d'utilisateur avec moins de trois lettres

### ISSUE THREAD

**Issue by Jibec** [maniackcrudelis/piwik_ynh#4]
Hello,

It looks like it isn't possible to have username with less than 3 letters, can you help me to fix this ?
Bonjour,

Il semble qu'un nom d'utilisateur avec moins de 3 lettres empêche la création de compte ... pourriez-vous m'aider pour résoudre ce problème ?

admin@yunohost:~$ sudo /var/www/piwik/console loginldap:synchronize-users --login=jb
Synchronizing 'jb'...  failed!

*************************
  Synchronized 0 users!  
*************************

Could not synchronize the following users in LDAP:
jb		The login must be between 3 and 100 characters long and contain only letters, numbers, or the characters '_' or '-' or '.' or '@' or '+'

**Comment by maniackcrudelis** [comment]
Bonjour,

c'est une limitation de piwik lui-même, je ne peux rien faire pour changer cela. Piwik impose un nom d'utilisateur comprenant entre 3 et 100 caractères.
Le seule chose que vous puissiez faire pour le moment, est de créer un autre utilisateur Yunohost avec un nom plus long pour lui installer piwik.
Dans un second temps, vous pouvez vous adresser aux équipes de développement de piwik.

**Comment by Jibec** [comment]
Can you please report this correction into your code ?
https://github.com/piwik/piwik/issues/7121

Thanks by advance

**Comment by maniackcrudelis** [comment]
C'est corrigé et testé par la mise à jour en 2.11.1

**Comment by Jibec** [comment]
Ok merci, je viens de tester à nouveau, il semble encore manquer un petit quelque chose : 

Error in Piwik: It appears the composer tool is not yet installed. You can install Composer in a few easy steps: In the piwik directory, run in the command line the following (eg. via ssh): curl -sS https://getcomposer.org/installer | php php composer.phar install This will initialize composer for Piwik and download libraries we use in vendor/* directory. Then reload this page to access your analytics reports. For more information check out this FAQ: How do I use Piwik from the Git repository?. Note: if for some reasons you cannot install composer, instead install the latest Piwik release from builds.piwik.org.
It appears the composer tool is not yet installed. You can install Composer in a few easy steps:
In the piwik directory, run in the command line the following (eg. via ssh):
curl -sS https://getcomposer.org/installer | php
php composer.phar install
This will initialize composer for Piwik and download libraries we use in vendor/* directory.
Then reload this page to access your analytics reports.

**Comment by maniackcrudelis** [comment]
Le dossier vendor s'est fait la malle durant le git push...
Je supporte pas git, je m'arrache les cheveux à chaque fois que je dois m'en servir...
Je vais essayer de corriger ça.

**Comment by maniackcrudelis** [comment]
Bon, git ne veut pas copier le dossier vendor, cela sans le moindre message bien sûr. Je déteste git...
J'ai passer la source en tar.gz, ça fonctionne à présent.

**Comment by Jibec** [comment]
works fine, thanks :)
