### ISSUE TITLE
Page blanche

### ISSUE THREAD

**Issue by adrien80080** [maniackcrudelis/piwik_ynh#6]
Bonjour !
j'ai installé Piwik a la racine du domaine (ex : piwik.domain.tld)
mais voilà que j'ai une jolie page blanche.

Je ne sais pas d'ou ça vient.
Une idée ?

**Comment by maniackcrudelis** [comment]
Corrigé dans ce commit https://github.com/maniackcrudelis/piwik_ynh/commit/635c6917982b7ca8b287fb7fcd875204ca3d83b6
